services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: etnair_user
      POSTGRES_PASSWORD: etnair_pass
      POSTGRES_DB: etnair_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - etnair-network
  
  api:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: etnair_user
      DB_PASSWORD: etnair_pass
      DB_NAME: etnair_db
      DATABASE_URL: postgresql://etnair_user:etnair_pass@db:5432/etnair_db
      JWT_SECRET: supersecretkey
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - etnair-network

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - etnair-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: harvey@etnair.xyz
      PGADMIN_DEFAULT_PASSWORD: harvey
    ports:
      - "5050:80"
    networks:
      - etnair-network
    depends_on:
      - db

networks:
  etnair-network:
    driver: bridge

volumes:
  db_data: