apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kentonnnn/etnair-api:latest
        env:
        - name: DB_HOST
          value: "postgresql"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: etnair-secrets
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: etnair-secrets
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: etnair-secrets
              key: POSTGRES_DB
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: etnair-secrets
              key: DATABASE_URL
        ports:
        - containerPort: 3000